backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "kontaktBlog"
    label: "Kontakt"
    folder: "src/pages/kontakt"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "kontakt-page",
        }
      # - { label: "Title", name: "title", widget: "string", default: "Kontakt" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { 
          label: "Social Media", 
          name: "socialmedia", 
          widget: "list", 
          summary: '{{fields.name}}',
          fields:
            [
              { label: "Name", name: "name", widget: "string" },
              { label: "Link", name: "link", widget: "string" },
            ]
        }
  - name: "aktuellesBlog"
    label: "Aktuelles"
    folder: "src/pages/aktuelles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "aktuelles-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "lebenslaufBlog"
    label: "Lebenslauf"
    folder: "src/pages/lebenslauf"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "lebenslauf-page",
        }
      - { label: "General", name: "body", widget: "markdown" }
      - { 
          label: "Entries", 
          name: "entries", 
          widget: "list", 
          summary: '{{fields.title}}',
          fields:
            [
              { label: Title, name: title, widget: string },
              { label: Start Date, name: startdate, widget: datetime, format: "DD.MM.YYYY", time_format: false },
              { label: End Date, name: enddate, widget: datetime, required: false, format: "DD.MM.YYYY", default: "00.00.0000", time_format: false },
              { label: Description, name: body, widget: markdown },
            ]
        }
  - name: "onTourBlog"
    label: "Jan unterwegs"
    folder: "src/pages/ontour"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "ontour-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "politikBlog"
    label: "Politik"
    folder: "src/pages/politik"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "politik-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "presseBlog"
    label: "Presse"
    folder: "src/pages/presse"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "presse-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "text" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string" }
  - name: "pressebilderBlog"
    label: "Pressebilder"
    folder: "src/pages/pressebilder"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "pressebilder-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: Intro,
          name: intro,
          widget: object,
          fields:
            [
              { label: Description, name: description, widget: text },
              {
                label: Fotos,
                name: blurbs,
                widget: list,
                fields:
                  [
                    { label: Image, name: image, widget: image },
                    { label: Alternativtext, name: alt, widget: string },
                    { label: Copyright, name: copyright, widget: string },
                  ],
              },
            ],
        }
  - name: "termineBlog"
    label: "Termine"
    folder: "src/pages/termine"
    create: true
    slug: "{{fields.date}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "termine-page",
        }
      - { label: "Event Title", name: "title", widget: string }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Event Link", name: "eventlink", widget: string, required: false}
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Description", name: "body", widget: "markdown" }
      - {
          label: Location,
          name: location,
          widget: object,
          fields:
            [
              {label: "Name", name: "name", widget: "string" },
              {label: "Link", name: "link", widget: "string" },
            ],
        }
  - name: "vorstellungBlog"
    label: "Vorstellung"
    folder: "src/pages/vorstellung"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "vorstellung-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "wahlkreisBlog"
    label: "Wahlkreis"
    folder: "src/pages/wahlkreis"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "wahlkreis-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "impressumBlog"
    label: "Impressum"
    folder: "src/pages/impressum"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "impressum-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Zuletzt aktualisiert:", name: "date", widget: "datetime" }
  - name: "datenschutzBlog"
    label: "Datenschutz"
    folder: "src/pages/datenschutz"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "datenschutz-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Zuletzt aktualisiert:", name: "date", widget: "datetime" }
  # - name: "pages"
  #   label: "Pages"
  #   files:
  #     - file: "src/pages/index.md"
  #       label: "Landing Page"
  #       name: "index"
  #       fields:
  #         - {
  #             label: "Template Key",
  #             name: "templateKey",
  #             widget: "hidden",
  #             default: "index-page",
  #           }
  #         - { label: Title, name: title, widget: string }
  #         - { label: Image, name: image, widget: image }
  #         # - { label: Heading, name: heading, widget: string }
  #         # - { label: Subheading, name: subheading, widget: string }
  #         - {
  #             label: Mainpitch,
  #             name: mainpitch,
  #             widget: object,
  #             fields:
  #               [
  #                 { label: Title, name: title, widget: string },
  #                 { label: Description, name: description, widget: text },
  #                 { label: Image, name: image, widget: image },
  #                 { label: Signature, name: signature, widget: image },
  #                 # { label: Description2, name: body, widget: markdown },
  #               ],
  #           }
  #         - { label: Description, name: description, widget: string }
  #         - {
  #             label: Intro,
  #             name: intro,
  #             widget: object,
  #             fields:
  #               [
  #                 { label: Heading, name: heading, widget: string },
  #                 { label: Description, name: description, widget: text },
  #                 {
  #                   label: Blurbs,
  #                   name: blurbs,
  #                   widget: list,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Text, name: text, widget: text },
  #                     ],
  #                 },
  #               ],
  #           }
  #         - {
  #             label: Main,
  #             name: main,
  #             widget: object,
  #             fields:
  #               [
  #                 { label: Heading, name: heading, widget: string },
  #                 { label: Description, name: description, widget: text },
  #                 {
  #                   label: Image1,
  #                   name: image1,
  #                   widget: object,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Alt, name: alt, widget: string },
  #                     ],
  #                 },
  #                 {
  #                   label: Image2,
  #                   name: image2,
  #                   widget: object,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Alt, name: alt, widget: string },
  #                     ],
  #                 },
  #                 {
  #                   label: Image3,
  #                   name: image3,
  #                   widget: object,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Alt, name: alt, widget: string },
  #                     ],
  #                 },
  #               ],
  #           }
  #     - file: "src/pages/about/index.md"
  #       label: "About"
  #       name: "about"
  #       fields:
  #         - {
  #             label: "Template Key",
  #             name: "templateKey",
  #             widget: "hidden",
  #             default: "about-page",
  #           }
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Body", name: "body", widget: "markdown" }
  #     - file: "src/pages/products/index.md"
  #       label: "Products Page"
  #       name: "products"
  #       fields:
  #         - {
  #             label: "Template Key",
  #             name: "templateKey",
  #             widget: "hidden",
  #             default: "product-page",
  #           }
  #         - { label: Title, name: title, widget: string }
  #         - { label: Image, name: image, widget: image }
  #         - { label: Heading, name: heading, widget: string }
  #         - { label: Description, name: description, widget: string }
  #         - {
  #             label: Intro,
  #             name: intro,
  #             widget: object,
  #             fields:
  #               [
  #                 { label: Heading, name: heading, widget: string },
  #                 { label: Description, name: description, widget: text },
  #                 {
  #                   label: Blurbs,
  #                   name: blurbs,
  #                   widget: list,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Text, name: text, widget: text },
  #                     ],
  #                 },
  #               ],
  #           }
  #         - {
  #             label: Main,
  #             name: main,
  #             widget: object,
  #             fields:
  #               [
  #                 { label: Heading, name: heading, widget: string },
  #                 { label: Description, name: description, widget: text },
  #                 {
  #                   label: Image1,
  #                   name: image1,
  #                   widget: object,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Alt, name: alt, widget: string },
  #                     ],
  #                 },
  #                 {
  #                   label: Image2,
  #                   name: image2,
  #                   widget: object,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Alt, name: alt, widget: string },
  #                     ],
  #                 },
  #                 {
  #                   label: Image3,
  #                   name: image3,
  #                   widget: object,
  #                   fields:
  #                     [
  #                       { label: Image, name: image, widget: image },
  #                       { label: Alt, name: alt, widget: string },
  #                     ],
  #                 },
  #               ],
  #           }
  #         - {
  #             label: Testimonials,
  #             name: testimonials,
  #             widget: list,
  #             fields:
  #               [
  #                 { label: Quote, name: quote, widget: string },
  #                 { label: Author, name: author, widget: string },
  #               ],
  #           }
  #         - { label: Full_image, name: full_image, widget: image }
  #         - {
  #             label: Pricing,
  #             name: pricing,
  #             widget: object,
  #             fields:
  #               [
  #                 { label: Heading, name: heading, widget: string },
  #                 { label: Description, name: description, widget: string },
  #                 {
  #                   label: Plans,
  #                   name: plans,
  #                   widget: list,
  #                   fields:
  #                     [
  #                       { label: Plan, name: plan, widget: string },
  #                       { label: Price, name: price, widget: string },
  #                       {
  #                         label: Description,
  #                         name: description,
  #                         widget: string,
  #                       },
  #                       { label: Items, name: items, widget: list },
  #                     ],
  #                 },
  #               ],
  #           }
